- name: Make sure that the prometheus directory is present
  ansible.builtin.file:
    path: /home/almalinux/stats
    state: directory
    owner: 65534
    group: 63334
  become: true
  become_user: root
- name: Make sure that the prometheus directory is present
  ansible.builtin.file:
    path: /home/almalinux/prometheus
    state: directory
- name: Put prometheus config in the right place
  ansible.builtin.copy:
    src: files/prometheus.yml
    dest: /home/almalinux/prometheus/prometheus.yml
- name: Put prometheus auth config in the right place
  ansible.builtin.copy:
    src: files/web.yml
    dest: /home/almalinux/prometheus/web.yml
- name: Create + start prometheus container 
  ansible.builtin.shell: 'docker run -d --restart=always  -p 9090:9090 -v /home/almalinux/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml -v /home/almalinux/prometheus/web.yml:/etc/prometheus/web.yml -v  /home/almalinux/stats:/stats --name=stats prom/prometheus:latest --config.file=/etc/prometheus/prometheus.yml --web.config.file=/etc/prometheus/web.yml --storage.tsdb.path=/stats --storage.tsdb.retention.time=90d'

