name: owu

services:
  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
# After you've set up the admin account, enable this instead
#      - 8080:8080   
      - 127.0.0.1:8080:8080
    env_file: ./open-webui.env
    volumes:
# If you want to use docker volumes (harder to backup) do this instead of bind mounts. Need to uncomment last line too.
#      - open-webui:/app/backend/data
      - ./open-webui:/app/backend/data:Z
  core:
    container_name: searxng-core
    image: docker.io/searxng/searxng:${SEARXNG_VERSION:-latest}
    restart: always
    env_file: ./searxng.env
    volumes:
      - ./core-config/:/etc/searxng/:Z
      - core-data:/var/cache/searxng/

  valkey:
    container_name: searxng-valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    volumes:
      - valkey-data:/data/

volumes:
  core-data:
  valkey-data:
#  open-webui:
