- name: Create directory
  ansible.builtin.file:
    path: /home/almalinux/litellm_setup
    state: directory
- name: Docker compose file
  ansible.builtin.template:
    dest: /home/almalinux/litellm_setup/docker-compose.yml
    src: templates/docker-compose.yml.j2
- name: Env file
  ansible.builtin.template:
    dest: /home/almalinux/litellm_setup/.env
    src: templates/env.j2
- name: Litellm config file
  ansible.builtin.template:
    dest: /home/almalinux/litellm_setup/config.yaml
    src: templates/config.yaml.j2
- name: Start LiteLLM with Docker compose
  ansible.building.shell: "cd /home/almalinux/litellm_setup; docker compose -d up"
