- name: Make sure that the cache directory is present
  ansible.builtin.file:
    path: /home/almalinux/cache
    state: directory
- name: Create + start VLLM container with Deepseek 4.1 Flash
  ansible.builtin.shell: 'docker run -d --restart=always --device nvidia.com/gpu=all -v /home/almalinux/cache:/root/.cache -p 127.0.0.1:5500:5500 --ipc=host --name=inference -e VLLM_ENGINE_READY_TIMEOUT_S=3600 -e VLLM_USE_RUST_FRONTEND=1 docker.io/vllm/vllm-openai:nightly --port 5500 --model deepseek-ai/DeepSeek-V4.1-Flash  --served-model-name UAITesting --tokenizer-mode deepseek_v41 --tensor-parallel-size 4  --enable-auto-tool-choice --tool-call-parser deepseek_v41 --reasoning-parser deepseek_v41 --mm-encoder-tp-mode data'
